language: python
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coverage flake8 flake8-docstrings flake8-import-order pytest PyYAML
script:
  - PYTHONPATH=`pwd` pytest -s -v test
notifications:
  email: false
